from __future__ import annotations

from typing import Protocol
from uuid import UUID

from tracking.domain.entities.device import Device
from tracking.domain.entities.geofence import Geofence
from tracking.domain.entities.position import Position
from tracking.domain.entities.vehicle import Vehicle


class DeviceRepository(Protocol):
    async def get(self, tenant_id: UUID, device_id: UUID) -> Device | None: ...
    async def get_by_imei(self, tenant_id: UUID, imei: str) -> Device | None: ...
    async def list(self, tenant_id: UUID) -> list[Device]: ...
    async def save(self, device: Device) -> None: ...
    async def delete(self, tenant_id: UUID, device_id: UUID) -> None: ...


class VehicleRepository(Protocol):
    async def get(self, tenant_id: UUID, vehicle_id: UUID) -> Vehicle | None: ...
    async def list(self, tenant_id: UUID) -> list[Vehicle]: ...
    async def save(self, vehicle: Vehicle) -> None: ...
    async def delete(self, tenant_id: UUID, vehicle_id: UUID) -> None: ...


class PositionRepository(Protocol):
    async def get_by_event_id(self, tenant_id: UUID, event_id: UUID) -> Position | None: ...
    async def latest_for_device(self, tenant_id: UUID, device_id: UUID) -> Position | None: ...
    async def list_recent(self, tenant_id: UUID, *, limit: int = 100) -> list[Position]: ...
    async def save(self, position: Position) -> None: ...
    async def list_unprocessed(self, tenant_id: UUID | None, *, limit: int = 50) -> list[Position]: ...
    async def mark_processed(self, position_id: UUID) -> None: ...


class GeofenceRepository(Protocol):
    async def get(self, tenant_id: UUID, geofence_id: UUID) -> Geofence | None: ...
    async def list(self, tenant_id: UUID) -> list[Geofence]: ...
    async def save(self, geofence: Geofence) -> None: ...
    async def delete(self, tenant_id: UUID, geofence_id: UUID) -> None: ...
